import type { Metadata } from "next";
import "./globals.css";

// Import the Geist fonts from the correct package
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import DashboardLayout from "@/components/layout/dashboard/dashboard";
import Footer from "@/components/landing-page/Footer";
export const metadata: Metadata = {
  title: "Kid's Nutri Garden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <DashboardLayout>
        {children}
        <Footer/>
        </DashboardLayout>
      </body>
    </html>
  );
}